# Site settings
title: Omics
header-img: img/home-bg.jpg
email:  omics@gmail.com
copyright_name: Jean-Philippe Villemin @ Omics
description: "Omics : Consulting in genomics and bioinformatics."
baseurl: ""
github_username:  ZheFrenchKitchen
url: "https://ZheFrenchKitchen.github.io/"
email_username:  jpvillemin@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
